const profile = {
  name: "Mukesh Dhale",
  initials: "MD",
  title: "Java Backend Developer",
  tagline: "Spring Boot · Microservices · REST APIs · AWS",
  location: "India",
  phone: "+91-9307014584",
  email: "mukeshdhale27@gmail.com",
  linkedin: "https://linkedin.com/in/mukesh-dhale",
  github: "https://github.com/Gitmukeshhh",
  summary:
    "Java Backend Developer with 3+ years of professional experience in designing, developing, and maintaining scalable backend applications and microservices. Strong expertise in Java, Spring Boot, Spring Cloud, Spring Security, REST APIs, Hibernate, JPA, Kafka, RabbitMQ, Redis, MySQL, PostgreSQL, and AWS. Experienced in microservices architecture, API development, database optimization, authentication and authorization, caching, asynchronous processing, cloud deployment, production support, and troubleshooting of enterprise applications. Strong understanding of OOP, SOLID principles, LLD, and Design Patterns, with knowledge of Large Language Models (LLMs) and Spring AI.",
  skills: [
    { category: "Programming", items: ["Java 8/11/17", "Groovy", "Python", "SQL"] },
    { category: "Frameworks", items: ["Spring Boot", "Spring MVC", "Spring Security", "Spring Data JPA", "Hibernate", "Spring Batch", "Spring Cloud", "Spring AOP"] },
    { category: "Architecture", items: ["Microservices", "REST APIs", "SOAP", "API Gateway", "Feign Client", "Event-Driven Arch."] },
    { category: "LLD & Design", items: ["OOD", "SOLID Principles", "LLD", "Design Patterns", "Factory", "Strategy", "Builder", "Singleton", "Observer"] },
    { category: "Messaging", items: ["Apache Kafka", "RabbitMQ", "Async Messaging"] },
    { category: "Databases", items: ["MySQL", "PostgreSQL", "Oracle", "MongoDB", "Redis", "OpenSearch", "Elasticsearch"] },
    { category: "Cloud & DevOps", items: ["AWS EC2", "ECS", "S3", "RDS", "Lambda", "WAF", "CloudWatch", "IAM", "Docker", "Git", "GitHub Actions", "Maven", "Gradle"] },
    { category: "Security", items: ["OAuth2", "JWT", "RBAC", "SSL/TLS", "Spring Security", "AWS WAF"] },
    { category: "AI / LLM", items: ["LLMs", "Spring AI"] },
    { category: "Tools", items: ["Swagger/OpenAPI", "Postman", "IntelliJ IDEA", "Eclipse", "JSON", "XML", "SFTP"] },
  ],
  experience: [
    {
      company: "JusTransform",
      role: "Software Engineer – Java Backend Developer",
      location: "Remote, India",
      duration: "Feb 2024 – Present",
      points: [
        "Designed and developed scalable Java microservices using Spring Boot, Spring Cloud, and REST APIs for an enterprise B2B SaaS integration platform.",
        "Applied LLD, SOLID principles, and Design Patterns to design maintainable, modular, and scalable backend components.",
        "Implemented secure authentication and authorization using Spring Security, OAuth2, JWT, and RBAC across backend services.",
        "Developed an OpenSearch-based search module for Business IDs, improving search accuracy and reducing API response latency.",
        "Implemented Redis caching with TTL-based eviction, reducing database load and improving response time for frequently accessed APIs.",
        "Worked on LookupV3 migration from MongoDB to MySQL, including data access changes, query optimization, and backend service modifications.",
        "Configured and managed AWS WAF and IAM policies to improve application security and control unauthorized traffic.",
        "Handled production issues through debugging, log analysis, root-cause analysis, and timely resolution of critical backend incidents.",
        "Participated in Java application modernization and version migration while maintaining application stability and backward compatibility.",
      ],
    },
    {
      company: "Alignbits LLC",
      role: "Software Engineer – Java Developer",
      location: "Remote, India",
      duration: "May 2023 – Jan 2024",
      points: [
        "Developed and maintained RESTful APIs and microservices using Java, Spring Boot, and Spring MVC for multiple client integrations.",
        "Built Groovy-based integration services and ETL pipelines for data transformation, processing, and system-to-system integration.",
        "Implemented Spring Batch jobs for large-scale data processing and automated backend workflows.",
        "Investigated and resolved production issues using debugging, log analysis, root-cause analysis, and performance troubleshooting.",
        "Developed unit and integration tests using JUnit 5 and Mockito to improve backend reliability and maintainability.",
        "Optimized MySQL and PostgreSQL queries using indexing, query analysis, and database performance tuning.",
      ],
    },
  ],
  projects: [
    {
      name: "BookMyShow",
      subtitle: "Scalable Microservices Ticket Booking System · Personal Project",
      tech: [
        "Java",
        "Spring Boot",
        "Spring Cloud (Eureka)",
        "API Gateway",
        "Spring Security",
        "JWT",
        "MySQL",
        "JPA/Hibernate",
        "RabbitMQ",
        "Docker",
      ],
      points: [
        "Developed a production-grade movie ticket booking platform using Java and Spring Boot microservices, enabling users to browse movies, select shows, and book tickets.",
        "Architected the system into independently deployable services — User, Movie, Booking, Payment, Notification, and Review — improving scalability, modularity, and maintainability.",
        "Implemented Spring Cloud Eureka for service discovery and an API Gateway for centralized request routing, load balancing, and traffic management.",
        "Secured APIs using Spring Security with JWT-based authentication, enabling role-based access control across services.",
        "Designed and optimized a normalized MySQL schema using JPA/Hibernate for users, shows, seats, and bookings.",
        "Integrated RabbitMQ for asynchronous, event-driven workflows such as booking confirmation notifications.",
        "Handled high-concurrency scenarios with seat locking and transaction management to prevent double booking during peak traffic.",
        "Containerized all services using Docker for consistent deployment and environment portability.",
      ],
    },
    {
      name: "JT Lookup Service v3",
      subtitle: "JusTransform",
      tech: ["Java", "Spring Boot", "Redis", "RabbitMQ", "REST API"],
      points: [
        "Designed and developed REST APIs with support for versioning, tenant isolation, and bulk data operations for a high-performance reference data microservice used across EDI transformations and mappers.",
        "Implemented Redis caching with TTL-based eviction, reducing database load and bringing response times under 20ms.",
        "Integrated RabbitMQ for event-driven cache invalidation to maintain data consistency across distributed systems.",
        "Resolved critical production issues related to stale data handling.",
      ],
    },
    {
      name: "JT-Search",
      subtitle: "Transaction Search Service · JusTransform",
      tech: ["Java 17", "Spring Boot 3", "MySQL", "JPA/Hibernate", "Native SQL", "JPA Specifications", "REST API", "AWS"],
      points: [
        "Developed advanced search APIs powering transaction search for enterprise users, with filtering by date range, transaction status, and connection details.",
        "Implemented permission-aware query logic using JPA Specifications and native SQL to ensure secure multi-tenant access.",
        "Optimized queries for large datasets to achieve sub-second response times.",
        "Handled complex access control scenarios while debugging and resolving production issues.",
      ],
    },
    {
      name: "OpenSearch Transaction Service",
      subtitle: "JusTransform",
      tech: ["Java 17", "Spring Boot", "AWS OpenSearch", "Java OpenSearch Client", "MySQL", "REST API"],
      points: [
        "Enabled real-time full-text search across transaction data by designing a scheduled batch indexing process to sync data from MySQL into AWS OpenSearch.",
        "Developed dynamic query builders using OpenSearch DSL to support flexible, accurate multi-filter search.",
        "Improved search accuracy by refining query logic and resolved data inconsistencies for reliable, high-performance search.",
      ],
    },
  ],
  education: [{ degree: "Bachelor of Engineering (B.E.)", duration: "2018 – 2022" }],
  certifications: [
    {
      name: "Certified by micro1 — AI Interview",
      issuer: "micro1",
      date: "August 22, 2026",
      image: "certificates/micro1-ai-interview.jpeg",
    },
  ],
};

export default profile;
